import { Platform, StyleSheet } from 'react-native';
// The wordmark shares screen 0's Avenir Next so the brand carries through the hand-off.
const wordmarkFont=Platform.select({ios:'AvenirNext-Regular',default:"'Avenir Next', Avenir, -apple-system, BlinkMacSystemFont, sans-serif"});
export const colors={ink:'#FFFFFF',secondary:'#BCBBC0',quiet:'#89898F',surface:'#141416',line:'#2B2B30',mint:'#C6ECDC'};
export const s=StyleSheet.create({
  desktop:{flex:1,backgroundColor:'#050505',alignItems:'center',justifyContent:'center'},desktopBrand:{position:'absolute',top:38,left:48,gap:10},desktopWordmark:{color:'#E9E9EB',fontSize:32,letterSpacing:-1.8,fontWeight:'400'},desktopLabel:{color:'#737378',fontSize:10,letterSpacing:2},desktopFoot:{position:'absolute',bottom:26,left:48,right:48,flexDirection:'row',justifyContent:'space-between'},desktopFootText:{color:'#737378',fontSize:11,letterSpacing:1},
  phone:{backgroundColor:'#000',overflow:'hidden',position:'relative'},phoneDesktop:{borderRadius:40,borderWidth:1,borderColor:'#232326',boxShadow:'0 24px 90px #00000080'},ambient:{position:'absolute',top:0,left:0,right:0,height:'40%',opacity:.8},orb:{position:'absolute',top:0,width:340,height:340},
  header:{position:'absolute',left:22,right:18,height:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',zIndex:5},wordmark:{fontFamily:wordmarkFont,fontSize:25,fontWeight:'400',letterSpacing:-1.5,color:colors.ink,marginLeft:6},headerControls:{flexDirection:'row',alignItems:'center'},iconButton:{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:24},progress:{height:2,width:100,backgroundColor:'#262629',borderRadius:2,marginLeft:25},progressFill:{height:2,backgroundColor:'#BBDCCD',borderRadius:2},
  keyboardLayer:{flex:1,pointerEvents:'box-none'},content:{flex:1,pointerEvents:'box-none'},orbTouch:{position:'absolute',width:250,height:250,borderRadius:150},welcomeCopy:{position:'absolute',left:24,right:24,alignItems:'center'},eyebrow:{fontSize:10,fontWeight:'500',letterSpacing:1.7,color:colors.secondary,lineHeight:16,textAlign:'center',marginBottom:16},welcomeTitle:{color:colors.ink,fontSize:44,letterSpacing:-2.1,lineHeight:48,fontWeight:'500',textAlign:'center'},welcomeSub:{color:colors.secondary,fontSize:14,lineHeight:22,textAlign:'center',marginTop:16},
  story:{position:'absolute',left:32,right:30},storyTitle:{fontSize:36,fontWeight:'500',lineHeight:41,letterSpacing:-1.35,color:colors.ink,textAlign:'center'},storySub:{fontSize:16,color:colors.secondary,lineHeight:25,textAlign:'center',marginTop:18},storyWhisper:{fontSize:16,lineHeight:25,color:colors.secondary,textAlign:'center'},promise:{position:'absolute',left:24,right:24},questionScroll:{paddingHorizontal:28,flexGrow:1},previous:{fontSize:14,lineHeight:22,color:'#929298',marginBottom:18},questionTitle:{fontSize:31,lineHeight:37,fontWeight:'500',letterSpacing:-1.1,color:colors.ink},questionHint:{fontSize:14,lineHeight:22,color:colors.secondary,marginTop:13,marginBottom:24},nameInput:{minHeight:62,backgroundColor:'#141416',borderWidth:1,borderColor:'#303035',borderRadius:18,borderCurve:'continuous',color:colors.ink,fontSize:21,paddingHorizontal:20,marginTop:16},
  choices:{gap:9},soundGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},soundTile:{width:'47.5%',height:86,borderRadius:22,borderCurve:'continuous',borderWidth:1,borderColor:'#28282D',backgroundColor:'#111113',padding:14,justifyContent:'space-between'},soundTileTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},soundCheck:{width:22,height:22,borderRadius:11,backgroundColor:colors.mint,alignItems:'center',justifyContent:'center'},
  planStop:{flexDirection:'row',gap:16,paddingBottom:20,position:'relative'},planRail:{position:'absolute',left:5,top:20,bottom:-6,width:1,backgroundColor:'#2F3533'},planDot:{width:11,height:11,borderRadius:6,marginTop:5,borderWidth:1.5,borderColor:'#5A5A60',backgroundColor:'#000'},planDotFirst:{borderColor:colors.mint,backgroundColor:colors.mint},planLabel:{fontSize:12,fontWeight:'600',letterSpacing:0.6,color:colors.secondary},planText:{fontSize:15,lineHeight:21,color:'#E4E4E8'},
  evidence:{marginTop:10,borderRadius:22,borderCurve:'continuous',backgroundColor:'#111113',borderWidth:1,borderColor:'#28282D',paddingVertical:16,paddingHorizontal:18,gap:8},evidenceText:{flex:1,fontSize:14,lineHeight:20,color:'#E4E4E8'},evidenceSource:{fontSize:11,lineHeight:16,color:'#929298',paddingLeft:30},choice:{minHeight:56,borderRadius:18,borderCurve:'continuous',borderWidth:1,borderColor:'#28282D',backgroundColor:'#111113',paddingVertical:15,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:13},selected:{borderColor:'#AFCBBF',backgroundColor:'#1B2420'},choicePressed:{backgroundColor:'#242427'},choiceNumber:{fontSize:11,color:'#929299',fontVariant:['tabular-nums']},choiceText:{fontSize:15,lineHeight:21,color:'#DFDFE3',flex:1},radio:{height:20,width:20,borderRadius:10,borderColor:'#727279',borderWidth:1,alignItems:'center',justifyContent:'center'},radioSelected:{backgroundColor:colors.mint,borderColor:colors.mint},
  checkbox:{borderRadius:6,borderCurve:'continuous'},radioDot:{width:8,height:8,borderRadius:4,backgroundColor:'#0C1812'},
  settingDescription:{fontSize:12,lineHeight:18,color:colors.secondary,marginTop:5},hapticPreview:{minHeight:44,alignItems:'center',justifyContent:'center',marginTop:8},hapticPreviewText:{fontSize:14,lineHeight:20,color:colors.mint},
  footer:{position:'absolute',bottom:0,left:0,right:0,paddingHorizontal:28,paddingTop:32},primary:{minHeight:58,paddingVertical:16,borderRadius:30,borderCurve:'continuous',overflow:'hidden',borderWidth:1,borderColor:'#E4E8E5',backgroundColor:'#E4E8E5',flexDirection:'row',alignItems:'center',justifyContent:'center',paddingHorizontal:24},primaryPressed:{transform:[{scale:.979}],opacity:.88},disabled:{opacity:.36},primaryText:{fontSize:16,lineHeight:22,color:'#101513',fontWeight:'600',letterSpacing:-.1},skip:{minHeight:44,alignItems:'center',justifyContent:'center',paddingTop:5},skipText:{fontSize:13,color:colors.secondary},footerMeta:{flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',marginTop:16},soundDot:{width:4,height:4,borderRadius:2,backgroundColor:'#B6CEC3'},footerNote:{fontSize:11,color:'#99999F'},
  reflection:{paddingHorizontal:28,alignItems:'center'},reflectionTitle:{fontSize:30,lineHeight:37,letterSpacing:-1,fontWeight:'500',color:colors.ink,textAlign:'center'},reflectionLine:{height:1,width:36,backgroundColor:'#4D5955',marginVertical:23},reflectionBody:{fontSize:15,lineHeight:25,color:colors.secondary,textAlign:'center'},microphoneCopy:{paddingHorizontal:25,alignItems:'center'},micBadge:{height:44,width:44,borderRadius:22,borderWidth:1,borderColor:'#3B5046',backgroundColor:'#14211B',alignItems:'center',justifyContent:'center',marginBottom:18},micTitle:{fontSize:30,lineHeight:35,letterSpacing:-1,color:colors.ink,fontWeight:'500',textAlign:'center'},micSub:{fontSize:15,lineHeight:23,textAlign:'center',color:colors.secondary,marginTop:14},permissionNote:{fontSize:12,lineHeight:19,color:'#98989F',textAlign:'center',marginTop:18},endMarker:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:14},endText:{fontSize:10,color:colors.secondary,letterSpacing:1.6},endLine:{width:25,height:1,backgroundColor:'#44484A'},
  settingsOverlay:{...StyleSheet.absoluteFill,zIndex:20,backgroundColor:'#00000088',justifyContent:'flex-end'},settingsPanel:{borderCurve:'continuous',backgroundColor:'#151517',borderTopWidth:1,borderColor:'#333337',borderTopLeftRadius:30,borderTopRightRadius:30,paddingHorizontal:27,paddingTop:22},settingsTitleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},settingsTitle:{fontSize:27,fontWeight:'500',letterSpacing:-.8,color:colors.ink},settingsSub:{fontSize:14,color:colors.secondary,marginTop:6,marginBottom:22},settingRow:{minHeight:76,paddingVertical:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderTopWidth:1,borderColor:'#2D2D32'},settingLabel:{fontSize:16,color:colors.ink},toggle:{width:50,height:30,borderRadius:16,backgroundColor:'#414148',padding:3},toggleOn:{backgroundColor:'#577266'},toggleThumb:{width:24,height:24,borderRadius:12,backgroundColor:'#F0F2F1'},settingsFootnote:{fontSize:12,lineHeight:19,color:colors.secondary,marginTop:12},audioError:{position:'absolute',top:80,left:24,right:24,color:'#DDD',fontSize:12,textAlign:'center'},
});
